name: Build Brunch using Github Actions
on:
  push:
    paths-ignore:
      - 'README.md'
concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true
jobs:
  prepare-kernels:
    name: Prepare Kernels
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.kernels.outputs.matrix }}
    steps:
      - name: Checkout Brunch source code
        uses: actions/checkout@v2
      - name: Download kernels and apply patches
        run: ./prepare_kernels.sh
      - name: Define kernels matrix
        id: kernels
        run: echo "::set-output name=matrix::$(echo [\"$(ls -d ./kernels/*  | cut -f3 -d'/' | sed -Ez '$ s/\n+$//' | sed -z 's#\n#","#g')\"])"
      - name: Compress kernels source files
        run: tar zcf /tmp/kernels-source.tar.gz kernels
      - name: Upload kernels source
        uses: actions/upload-artifact@v2
        with:
          name: kernels-source
          path: /tmp/kernels-source.tar.gz
          if-no-files-found: error
  build-kernels:
    name: Build Kernels
    needs: prepare-kernels
    runs-on: ubuntu-latest
    strategy:
        matrix:
            kernel: ${{ fromJson(needs.prepare-kernels.outputs.matrix) }}
    steps:
      - name: Install dependencies
        run: sudo apt-get update && DEBIAN_FRONTEND=noninteractive sudo apt-get -y install libncurses-dev gawk flex bison openssl libssl-dev dkms libelf-dev libudev-dev libpci-dev libiberty-dev autoconf sbsigntool
      - name: Checkout Brunch source code
        uses: actions/checkout@v2
      - name: Download kernels source
        uses: actions/download-artifact@v2
        with:
          name: kernels-source
          path: /tmp
      - name: Extract kernels source files
        run: |
          tar -zxf /tmp/kernels-source.tar.gz
          rm -f /tmp/kernels-source.tar.gz
      - name: Install Secure Boot certificate
        env:
          BRUNCH_PRIV: ${{ secrets.BRUNCH_PRIV }}
          BRUNCH_PEM: ${{ secrets.BRUNCH_PEM }}
        run: |
          sudo ln -s $RUNNER_TEMP /persist
          mkdir /persist/keys
          echo "$BRUNCH_PRIV" | base64 -d > /persist/keys/brunch.priv
          echo "$BRUNCH_PEM" | base64 -d > /persist/keys/brunch.pem
      - name: Build kernels
        run: ./build_kernels.sh ${{ matrix.kernel }}
      - name: Clear keys
        run: rm -r /persist/keys
      - name: Compress built kernel
        run: tar zcf /tmp/built-kernel-${{ matrix.kernel }}.tar.gz kernels/${{ matrix.kernel }}
      - name: Upload kernels source
        uses: actions/upload-artifact@v2
        with:
          name: built-kernel-${{ matrix.kernel }}
          path: /tmp/built-kernel-${{ matrix.kernel }}.tar.gz
          if-no-files-found: error
  build-brunch:
    name: Build Brunch
    needs: build-kernels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Brunch source code
        uses: actions/checkout@v2
      - name: Apply Chuwi Hi12 specific modifications
        run: |
          # Goodix touchscreen driver from kernel 5.17
          rm -rf external-drivers/goodix/goodix.c
          curl -L "https://github.com/rodriguezst/goodix-backport/raw/master/Makefile" -o external-drivers/goodix/Makefile
          curl -L "https://github.com/rodriguezst/goodix-backport/raw/master/goodix_ts.c" -o external-drivers/goodix/goodix_ts.c
          curl -L "https://github.com/rodriguezst/goodix-backport/raw/master/goodix.h" -o external-drivers/goodix/goodix.h
          curl -L "https://github.com/rodriguezst/goodix-backport/raw/master/goodix_fwupload.c" -o external-drivers/goodix/goodix_fwupload.c
          # alsa-ucm-conf from v1.2.1
          rm -rf alsa-ucm-conf
          curl -L "https://github.com/alsa-project/alsa-ucm-conf/archive/refs/tags/v1.2.1.zip" -o alsa-ucm-conf.zip
          unzip alsa-ucm-conf.zip "*/ucm*"
          mv alsa-ucm-conf-*/ alsa-ucm-conf
      - name: Download built kernels
        uses: actions/download-artifact@v2
        with:
          path: /tmp
      - name: Copy built kernels
        run: |
          for file in /tmp/built-kernel-*/built-kernel-*.tar.gz
          do
            tar zxf $file
            rm -f $file
          done
          rm -r /tmp/kernels-source/kernels-source.tar.gz
      - name: Build brunch
        run: sudo bash build_brunch.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: brunch-build
          path: out/brunch_r*.tar.gz
          if-no-files-found: error
  release:
    name: Make a Brunch release
    permissions:
      contents: write
    needs: build-brunch
    runs-on: ubuntu-latest
    steps:
      - name: Download built artifacts
        uses: actions/download-artifact@v2
        with:
          name: brunch-build
      - name: Identify custom version
        if: ${{ (github.repository != 'sebanc/brunch') && (github.repository != 'sebanc/brunch-unstable') }}
        run: echo "RELEASE_VERSION_TYPE=custom" >> $GITHUB_ENV
      - name: Identify unstable version
        if: ${{ (github.repository == 'sebanc/brunch-unstable') }}
        run: echo "RELEASE_VERSION_TYPE=unstable" >> $GITHUB_ENV
      - name: Identify stable version
        if: ${{ (github.repository == 'sebanc/brunch') }}
        run: echo "RELEASE_VERSION_TYPE=stable" >> $GITHUB_ENV
      - name: Generate release details
        run: |
          RELEASE_FILE=$(ls brunch_r*.tar.gz)
          RELEASE_VERSION=$(echo "$RELEASE_FILE" | cut -d'.' -f1 | cut -d'_' -f2)
          RELEASE_DATE=$(echo "$RELEASE_FILE" | cut -d'.' -f1 | cut -d'_' -f3)
          echo "Found brunch release: ${RELEASE_FILE} with version ${RELEASE_VERSION} and date ${RELEASE_DATE}"
          mv "brunch_${RELEASE_VERSION}_${RELEASE_DATE}.tar.gz" "brunch_${RELEASE_VERSION}_${RELEASE_VERSION_TYPE}_${RELEASE_DATE}.tar.gz"
          echo "Brunch release renamed from brunch_${RELEASE_VERSION}_${RELEASE_DATE}.tar.gz to brunch_${RELEASE_VERSION}_${RELEASE_VERSION_TYPE}_${RELEASE_DATE}.tar.gz"
          echo "RELEASE_FILE=brunch_${RELEASE_VERSION}_${RELEASE_VERSION_TYPE}_${RELEASE_DATE}.tar.gz" >> $GITHUB_ENV
          echo "RELEASE_TAG=${RELEASE_VERSION}-${RELEASE_VERSION_TYPE}-${RELEASE_DATE}-HI12" >> $GITHUB_ENV
          echo "RELEASE_NAME=Brunch ${RELEASE_VERSION} ${RELEASE_VERSION_TYPE} ${RELEASE_DATE}" >> $GITHUB_ENV          
      - name: Create a release and upload artifacts as assets
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.RELEASE_FILE }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          tag: "${{ env.RELEASE_TAG }}"
          name: "${{ env.RELEASE_NAME }}"
          commit: "${{ github.ref_name }}"
          body: "${{ github.event.head_commit.message }}"
